import Head from "next/head";
import Image from "next/image";
import getData from "./api/nasaData";

export async function getServerSideProps() {
  const data = await getData();
  return {
    props: { data },
  };
}

type Data = {
  date: string;
  explanation: string;
  hdurl: string;
};

export default function Home({ data }: { data: Data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Todays NASA DATA</h1>
        <p>{data.date}</p>
        <p>{data.explanation}</p>
        <Image src={data.hdurl} alt={""} width={1200} height={500} />
      </main>
    </>
  );
}
